version: '3'

services:
  server:
    image: nginx:alpine
    restart: always
    networks: 
      - static-dev-network
    ports:
      - "127.0.0.1:17088:80"
    volumes:
      - ./data:/srv
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  static-dev-network: